name: attend
description: Attendance app

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.32.0
  cloud_firestore: ^4.9.0
  connectivity_plus: ^4.0.1
  network_info_plus: ^6.0.0
  permission_handler: 12.0.1
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  intl: ^0.20.2
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
