name: Infivity
description: Attendance app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.32.0
  cloud_firestore: ^4.9.0
  connectivity_plus: ^4.0.1
  network_info_plus: ^6.0.0
  permission_handler: 12.0.1
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  intl: ^0.20.2
  location: ^8.0.1
  device_info_plus: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/infivity.png"
  adaptive_icon_foreground: "lib/assets/icons/infivity.png"
  adaptive_icon_background: "#4e2780"

flutter_native_splash:
  color: "#4e2780"
  image: "lib/assets/icons/infivity2.png"
  android: true
  ios: true
  web: true

  
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  web_image_mode: cover

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/infivity.png
    - lib/assets/icons/infivity2.png
